# Generated by Django 5.2.3 on 2026-05-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True,
                help_text="ID devuelto por la pasarela de pago.",
                max_length=200,
                verbose_name="ID de transacción (pasarela)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Generada automáticamente. Se usa en pasarelas de pago.",
                max_length=32,
                unique=True,
                verbose_name="Referencia única",
            ),
        ),
    ]
