# Generated by Django 5.2.3 on 2026-05-03 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productvariant'),
        ('orders', '0002_alter_order_payment_id_alter_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant', verbose_name='Variante'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_color',
            field=models.CharField(blank=True, max_length=60, verbose_name='Color comprado'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_sku',
            field=models.CharField(blank=True, max_length=80, verbose_name='SKU comprado'),
        ),
    ]
