# Generated by Django 5.2.3 on 2026-05-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="country",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="País de origen"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="brands/logos/", verbose_name="Logo"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="website",
            field=models.URLField(blank=True, verbose_name="Sitio web"),
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descripción corta"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Clase de Font Awesome o similar. Ej: fa-camera-security",
                max_length=80,
                verbose_name="Ícono (clase CSS, ej: fa-camera)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="compatible_with",
            field=models.ManyToManyField(
                blank=True,
                help_text="Otros productos compatibles o complementarios.",
                related_name="compatible_products",
                to="catalog.product",
                verbose_name="Compatible con",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="connectivity",
            field=models.CharField(
                blank=True,
                help_text="Ej: IP/PoE, WiFi, 4G, Analógico, RS-485",
                max_length=100,
                verbose_name="Conectividad",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="datasheet_url",
            field=models.URLField(
                blank=True,
                help_text="Enlace al PDF oficial del fabricante.",
                verbose_name="Ficha técnica (URL)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Aparece en la sección destacada del home.",
                verbose_name="Destacado en inicio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="model_number",
            field=models.CharField(
                blank=True,
                help_text="Código del fabricante. Ej: DS-2CD2143G2-I",
                max_length=100,
                verbose_name="Modelo / Referencia",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="power_supply",
            field=models.CharField(
                blank=True,
                help_text="Ej: 12V DC, PoE 802.3af, 110-220V AC",
                max_length=80,
                verbose_name="Alimentación eléctrica",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="requires_installation",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el producto necesita instalación técnica.",
                verbose_name="Requiere instalación profesional",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="resolution",
            field=models.CharField(
                blank=True,
                help_text="Ej: 4MP, 8MP, 4K, 1080p",
                max_length=50,
                verbose_name="Resolución",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_months",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Período de garantía oficial del fabricante.",
                verbose_name="Garantía (meses)",
            ),
        ),
    ]
