# Generated by Django 5.2.3 on 2026-05-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_brand_country_brand_logo_brand_website_and_more"),
        ("catalog", "0002_category_hierarchy"),
    ]

    operations = []
