# Generated by Django 5.2.3 on 2026-05-02 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_merge_20260502_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__name', 'order', 'name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si está desactivada, no se muestra al cliente.', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='category',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp de la última vez que sync_content actualizó este registro.', null=True, verbose_name='Última sincronización'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en menús y listados.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Si está vacío, es categoría principal. Si tiene valor, es subcategoría.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Categoría padre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='source_path',
            field=models.CharField(blank=True, help_text='Ruta en content/ que originó esta categoría (auto-llenada por sync_content).', max_length=500, verbose_name='Ruta en disco'),
        ),
    ]
