# Generated by Django 5.2.3 on 2026-05-03 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80, unique=True, verbose_name='SKU')),
                ('color', models.CharField(blank=True, help_text='Etiqueta visible (ej: rojo, azul). Tambien usada para matchear imagenes por nombre de archivo.', max_length=60, verbose_name='Color')),
                ('name', models.CharField(blank=True, help_text='Si esta vacio, se muestra "<producto> - <color>".', max_length=200, verbose_name='Nombre visible')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de producto',
                'ordering': ['product', 'color'],
                'unique_together': {('product', 'color')},
            },
        ),
    ]
