# Generated by Django 5.2.3 on 2026-05-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio')], db_index=True, default='product', help_text='Producto físico (con stock) o servicio (instalación, monitoreo, etc.).', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Especificaciones técnicas en formato JSON. Ej: {"resolución": "4K", "garantía": "12 meses"}', verbose_name='Especificaciones (JSON)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
        ),
    ]
