# Generated by Django 5.2.3 on 2026-05-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_specifications_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Subcategoría opcional dentro de la categoría (ej: CCTV dentro de Instalaciones).', max_length=120, verbose_name='Subcategoría'),
        ),
    ]
