# Generated by Django 5.2.3 on 2026-05-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Imagen externa por URL (alternativa a subir un archivo).', max_length=500, null=True, verbose_name='URL de imagen'),
        ),
    ]
